// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectApp.Persistence;

#nullable disable

namespace ProjectApp.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20241010095402_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjectApp.Persistence.ProjectDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProjectDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreateDate = new DateTime(2024, 10, 10, 11, 53, 59, 586, DateTimeKind.Local).AddTicks(9250),
                            Title = "Learn ASP.NET Core with MVC",
                            UserName = "julg@kth.se"
                        });
                });

            modelBuilder.Entity("ProjectApp.Persistence.TaskDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Follow the turtles",
                            LastUpdated = new DateTime(2024, 10, 10, 11, 53, 59, 586, DateTimeKind.Local).AddTicks(9630),
                            ProjectId = -1,
                            Status = 1
                        },
                        new
                        {
                            Id = -2,
                            Description = "Do it yourself",
                            LastUpdated = new DateTime(2024, 10, 10, 11, 53, 59, 586, DateTimeKind.Local).AddTicks(9640),
                            ProjectId = -2,
                            Status = 0
                        });
                });

            modelBuilder.Entity("ProjectApp.Persistence.TaskDb", b =>
                {
                    b.HasOne("ProjectApp.Persistence.ProjectDb", "ProjectDb")
                        .WithMany("TaskDbs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectDb");
                });

            modelBuilder.Entity("ProjectApp.Persistence.ProjectDb", b =>
                {
                    b.Navigation("TaskDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
